### ISSUE TITLE
HomeBridge安装完成后登录账号  提示异常

### ISSUE THREAD

**Issue by Zikkkkkk** [baranwang/homebridge-plugin-haier#6]
作者你好
HomeBridge安装完成后登录账号  日志输出：
<img width="954" alt="image" src="https://github.com/baranwang/homebridge-plugin-haier/assets/18693426/09fe4acb-ef42-460f-9b21-f044b0953b09">
请问 这个是哪里配置错了吗，账号密码全部都正确

**Comment by Zikkkkkk** [comment]
补充：用户名应该是手机号吧？

**Comment by baranwang** [comment]
是手机号，我现在在外出差，下周回去看看在 2023年11月1日，21:57，AsIm ***@***.***> 写道：﻿
补充：用户名应该是手机号吧？

**Comment by Zikkkkkk** [comment]
好的感谢

**Comment by baranwang** [comment]
试一下 1.2.0 呢？
